### ISSUE TITLE
Create our own wildfire detection algorithm, if necessary

### ISSUE THREAD

**Issue by camenpihor** [joyprojects/wildfire#24]
## Checklist

- Select Project Label
- Select Sub-Project Milestone

## Feature Description

We want to create a good wildfire detection algorithm in order to create a labelled dataset for learning wildfire occurrence. If the algorithm implemented in [this paper](https://www.researchgate.net/profile/Xu_Zhong7/publication/318455389_Real-time_wildfire_detection_and_tracking_in_Australia_using_geostationary_satellite_Himawari-8/links/5ac2b6af45851584fa773b76/Real-time-wildfire-detection-and-tracking-in-Australia-using-geostationary-satellite-Himawari-8.pdf) is not good enough, we should make our own.

## Developer Notes

- We may want to write a paper on this, so the code, analysis, and model should be clean, reproducible, and legible
- Output should be a boolean

## Known Blockers

- #20, #21, #22, #23 

## Sub-Tasks

- [ ] document the ways in which the algorithm in the paper is bad

## Acceptance Criteria

- [ ] implement
- [ ] tested
- [ ] metrics are calculated for it and compared are better than those calculated for the paper's algorithm
- [ ] is not too slow
