### ISSUE TITLE
Create .bashrc for the HPC environment

### ISSUE THREAD

**Issue by camenpihor** [joyprojects/wildfire#28]
## Checklist

- Select Project Label
- Select Sub-Project Milestone

## Feature Description

We are going to be using the NAS HPC environment a lot, so we should at least make it comfortable.

## Developer Notes

- Should be thoughtful of other users' preferences
- I suggest hosted the .bashrc in this repository

## Known Blockers

- None

## Sub-Tasks

- [x] copying files from local
- [x] copying files to local
- [x] aliases for conda
- [x] terminal look and feel

## Acceptance Criteria

- [x] works
- [x] accepted by team members

**Comment by camenpihor** [comment]
created https://github.com/camenpihor/dotfiles/tree/master/nasa (should we add to this repository? @Ferrumofomega )
