### ISSUE TITLE
Create .vimrc for the HPC environment

### ISSUE THREAD

**Issue by camenpihor** [joyprojects/wildfire#29]
## Checklist

- Select Project Label
- Select Sub-Project Milestone

## Feature Description

We are going to need to use the NAS HPC environment a lot, so we should at least make it comfortable. Create a .vimrc to make the environment easier to work with.

## Developer Notes

- Should be thoughtful of others' preferences
- I suggest hosting this file in this repository

## Known Blockers

- None

## Sub-Tasks

- [x] look and feel of vim
- [x] good for python development

## Acceptance Criteria

- [x] accepted by team
- [x] works

**Comment by camenpihor** [comment]
create https://github.com/camenpihor/dotfiles/tree/master/nasa (should we add to this repository? @Ferrumofomega )
