### ISSUE TITLE
Create documentation for SSH'ing into the NAS HPC environment

### ISSUE THREAD

**Issue by camenpihor** [joyprojects/wildfire#33]
## Checklist

- Select Project Label
- Select Sub-Project Milestone

## Feature Description

SSH'ing into NAS is hard... We should document our learnings.

## Developer Notes

- None

## Known Blockers

- None

## Sub-Tasks

- [x] create a sample config file
- [x] start document for learnings

## Acceptance Criteria

- [x] at least add links to official documentation

**Comment by Ferrumofomega** [comment]
Draft here [https://github.com/joyprojects/wildfire/tree/ssh-config-example](url)

**Comment by camenpihor** [comment]
Done!
